# -*- coding: utf-8 -*-
"""Data visualisation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m2DHn0-CafVUGLgFu3pazGbjKAdBSf99
"""

import matplotlib.pyplot as plt

import numpy as np

x=np.array([1,2,3,4,5])
y=x**2+3

print(x,y)

plt.plot(x,y)

plt.style.available

plt.style.use('seaborn-v0_8')

plt.title('Quadratic Equation')
plt.xlabel('x')
plt.ylabel('y')
plt.plot(x,y,label='y=x^2+3')
plt.legend()
plt.show()

plt.title('Quadratic Equation')
plt.xlabel('x')
plt.ylabel('y')
plt.scatter(x,y,label='y=x^2+3')
plt.legend()
plt.show()

